# docker-compose.yml (remove the version line as it's obsolete)
services:
  db:
    image: pgvector/pgvector:pg16
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PG_DATABASE: ${PG_DATABASE}
      PG_HOST: db
      PG_PORT: ${PG_PORT:-5432}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    # Keep container running for manual commands
    tty: true
    stdin_open: true

volumes:
  pgdata: